version: '3.8'

services:
    dev-db:
        image: postgres:15-alpine
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres123
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - freecodecamp

volumes:
    postgres_data:

networks:
    freecodecamp:
